<a href="https://colab.research.google.com/github/MariaPosadaBotero/Entregas-del-proyecto-de-AI-para-ingenieros---Udea-2025-2/blob/main/01-exploraci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####Integrantes:


*   Maria Isabel Posada Botero. CC: 1040355409.
*   Diana Milena Oquendo Restrepo. CC: 1193123469.






>

In [46]:
# Crear carpeta oculta para las credenciales
!mkdir -p ~/.kaggle

# Copiar el archivo kaggle.json que subiste
!cp kaggle.json ~/.kaggle/

# Ajustar permisos de seguridad (muy importante)
!chmod 600 ~/.kaggle/kaggle.json

In [48]:
# Descargo la libreria de kaggle
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2025.8.3)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.3)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [47]:
#Se descarga los datos de la competencia
!kaggle competitions download -c udea-ai-4-eng-20252-pruebas-saber-pro-colombia
!unzip udea-ai-4-eng-20252-pruebas-saber-pro-colombia.zip

udea-ai-4-eng-20252-pruebas-saber-pro-colombia.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  udea-ai-4-eng-20252-pruebas-saber-pro-colombia.zip
replace submission_example.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [49]:
#Importar la libreria pandas
import pandas as pd

#Cargar el dataset de entrenamiento
df = pd.read_csv("train.csv")

#Ver dimensiones del dataset
print("Numero de filas y columnas:", df.shape)

Numero de filas y columnas: (692500, 21)

In [50]:
#Mostrar las primeras filas
print("\nPrimeras filas del dataset:")
display(df.head())

Primeras filas del dataset:

,ID,PERIODO_ACADEMICO,E_PRGM_ACADEMICO,E_PRGM_DEPARTAMENTO,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENEINTERNET,F_EDUCACIONPADRE,F_TIENELAVADORA,...,E_PRIVADO_LIBERTAD,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,F_TIENEINTERNET.1,F_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,INDICADOR_1,INDICADOR_2,INDICADOR_3,INDICADOR_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

In [51]:
#Monstrar la Información general de las columnas
print("\nInformación general de las columnas:")
df.info()

Información general de las columnas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692500 entries, 0 to 692499
Data columns (total 21 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ID                           692500 non-null  int64
 1   PERIODO_ACADEMICO            692500 non-null  int64
 2   E_PRGM_ACADEMICO             692500 non-null  object
 3   E_PRGM_DEPARTAMENTO          692500 non-null  object
 4   E_VALORMATRICULAUNIVERSIDAD  686213 non-null  object
 5   E_HORASSEMANATRABAJA         661643 non-null  object
 6   F_ESTRATOVIVIENDA            660363 non-null  object
 7   F_TIENEINTERNET              665871 non-null  object
 8   F_EDUCACIONPADRE             669322 non-null  object
 9   F_TIENELAVADORA              652727 non-null  object
 10  F_TIENEAUTOMOVIL             648877 non-null  object
 11  E_PRIVADO_LIBERTAD           692500 non-null  object
 12  E_PAGOMATRICULAPROPIO        686002 non-null  object
 13  F_TIENECOMPUTADOR            654397 non-null  object
 14  F_TIENEINTERNET.1            665871 non-null  object
 15  F_EDUCACIONMADRE             668836 non-null  object
 16  RENDIMIENTO_GLOBAL           692500 non-null  object
 17  INDICADOR_1                  692500 non-null  float64
 18  INDICADOR_2                  692500 non-null  float64
 19  INDICADOR_3                  692500 non-null  float64
 20  INDICADOR_4                  692500 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 111.0+ MB

In [52]:
#Revisar los valores faltantes
print("\nValores faltantes por columna:")
print(df.isnull().sum())

Valores faltantes por columna:
ID                                 0
PERIODO_ACADEMICO                  0
E_PRGM_ACADEMICO                   0
E_PRGM_DEPARTAMENTO                0
E_VALORMATRICULAUNIVERSIDAD     6287
E_HORASSEMANATRABAJA           30857
F_ESTRATOVIVIENDA              32137
F_TIENEINTERNET                26629
F_EDUCACIONPADRE               23178
F_TIENELAVADORA                39773
F_TIENEAUTOMOVIL               43623
E_PRIVADO_LIBERTAD                 0
E_PAGOMATRICULAPROPIO           6498
F_TIENECOMPUTADOR              38103
F_TIENEINTERNET.1              26629
F_EDUCACIONMADRE               23664
RENDIMIENTO_GLOBAL                 0
INDICADOR_1                        0
INDICADOR_2                        0
INDICADOR_3                        0
INDICADOR_4                        0
dtype: int64

##EXPLORACIÓN SENCILLA DE LOS DATOS
A continuación se realizará una exploración a los datos de las pruebas Saber Pro 2025-2

In [53]:
#Lista completa de programas académicos con número de estudiantes
programas_completos = df["E_PRGM_ACADEMICO"].value_counts()

print("\nLista completa de estudiantes por programa académico:")
print(programas_completos)

# Número de programas distintos
print(f"\nNúmero total de programas académicos: {df['E_PRGM_ACADEMICO'].nunique()}")

# Número total de estudiantes
print(f"Número total de estudiantes: {df['E_PRGM_ACADEMICO'].count()}")

Lista completa de estudiantes por programa académico:
E_PRGM_ACADEMICO
DERECHO                                                   53244
ADMINISTRACION DE EMPRESAS                                51902
CONTADURIA PUBLICA                                        39664
PSICOLOGIA                                                31932
INGENIERIA INDUSTRIAL                                     28481
                                                          ...
DEPORTE Y ACTIVIDADA FISICA                                   1
QUIMICA Y FARMACIA                                            1
LICENCIATURA EN EDUCACON FISICA, RECREACION Y DEPORTES        1
COMUNICACIÓN SOCIAL Y PERIODISMO                              1
PROFESIONAL EN INVESTIGACIÓN CRIMINAL                         1
Name: count, Length: 948, dtype: int64

Número total de programas académicos: 948
Número total de estudiantes: 692500

In [54]:
# Top 10 programas con más estudiantes
top10_programas = df["E_PRGM_ACADEMICO"].value_counts().head(10)

print("\nTop 10 programas académicos con más estudiantes:")
print(top10_programas)

Top 10 programas académicos con más estudiantes:
E_PRGM_ACADEMICO
DERECHO                       53244
ADMINISTRACION DE EMPRESAS    51902
CONTADURIA PUBLICA            39664
PSICOLOGIA                    31932
INGENIERIA INDUSTRIAL         28481
ADMINISTRACIÓN DE EMPRESAS    24777
INGENIERIA CIVIL              19487
MEDICINA                      18099
PSICOLOGÍA                    17377
INGENIERIA DE SISTEMAS        17150
Name: count, dtype: int64

In [55]:
# Número de estudiantes por departamento
estudiantes_departamento = df["E_PRGM_DEPARTAMENTO"].value_counts()

print("\nDistribución de estudiantes por departamento:")
print(estudiantes_departamento)

# Número total de departamentos distintos
print(f"\nNúmero total de departamentos: {df['E_PRGM_DEPARTAMENTO'].nunique()}")

Distribución de estudiantes por departamento:
E_PRGM_DEPARTAMENTO
BOGOTÁ             282159
ANTIOQUIA           83607
VALLE               44588
ATLANTICO           41020
SANTANDER           28828
NORTE SANTANDER     22588
BOLIVAR             20629
BOYACA              14048
CUNDINAMARCA        14018
NARIÑO              13454
RISARALDA           12679
CORDOBA             12188
TOLIMA              11921
CALDAS              11640
CAUCA               11471
HUILA                9995
MAGDALENA            9512
SUCRE                8674
CESAR                8279
QUINDIO              8229
META                 7910
LA GUAJIRA           4778
CHOCO                4289
CAQUETA              2659
CASANARE             1852
PUTUMAYO              795
ARAUCA                589
AMAZONAS               40
GUAVIARE               37
VAUPES                 14
SAN ANDRES             10
Name: count, dtype: int64

Número total de departamentos: 31

In [57]:
# Agrupamos por programa académico y rango de matrícula
matricula_por_programa = (
    df.groupby(["E_PRGM_ACADEMICO", "E_VALORMATRICULAUNIVERSIDAD"])
      .size()
      .reset_index(name="Conteo")   # convierte índice en columnas
)

# Mostrar el resultado (solo primeras 20 filas)
print(matricula_por_programa.head(20))

                                  E_PRGM_ACADEMICO  \
0   3°  CICLO PROFESIONAL NEGOCIOS INTERNACIONALES
1   3°  CICLO PROFESIONAL NEGOCIOS INTERNACIONALES
2                       ACTIVIDAD FISICA Y DEPORTE
3                       ACTIVIDAD FISICA Y DEPORTE
4                       ACTIVIDAD FISICA Y DEPORTE
5                       ACTIVIDAD FISICA Y DEPORTE
6                                      ACUICULTURA
7                                      ACUICULTURA
8                                   ADMINISTRACION
9                                   ADMINISTRACION
10                                  ADMINISTRACION
11                                  ADMINISTRACION
12                                  ADMINISTRACION
13                                  ADMINISTRACION
14                                  ADMINISTRACION
15                                  ADMINISTRACION
16                      ADMINISTRACION  FINANCIERA
17                      ADMINISTRACION  FINANCIERA
18                       ADMINISTRACION & SERVICIO
19                      ADMINISTRACION AERONAUTICA

                 E_VALORMATRICULAUNIVERSIDAD  Conteo
0     Entre 1 millón y menos de 2.5 millones      42
1          Entre 500 mil y menos de 1 millón      27
2     Entre 1 millón y menos de 2.5 millones      87
3   Entre 2.5 millones y menos de 4 millones      70
4   Entre 4 millones y menos de 5.5 millones       1
5          Entre 500 mil y menos de 1 millón       4
6                           Menos de 500 mil      70
7                          No pagó matrícula       9
8     Entre 1 millón y menos de 2.5 millones       6
9   Entre 2.5 millones y menos de 4 millones      12
10  Entre 4 millones y menos de 5.5 millones      38
11  Entre 5.5 millones y menos de 7 millones       3
12         Entre 500 mil y menos de 1 millón       8
13                          Menos de 500 mil       9
14                         Más de 7 millones       4
15                         No pagó matrícula      37
16    Entre 1 millón y menos de 2.5 millones       7
17  Entre 2.5 millones y menos de 4 millones      67
18                         Más de 7 millones      29
19    Entre 1 millón y menos de 2.5 millones       1

In [58]:
#Conocer si hay algún estudiante privado de la libertad
# Crear la tabla cruzada
tabla = pd.crosstab(df['E_PRGM_ACADEMICO'], df['E_PRIVADO_LIBERTAD'])

# Renombrar las columnas para mayor claridad
tabla = tabla.rename(columns={0: 'No_Privados', 1: 'Privados'})

# Agregar una columna con el total
tabla['Total'] = tabla.sum(axis=1)

# Mostrar la tabla final
print(tabla)

E_PRIVADO_LIBERTAD                                  N  S  Total
E_PRGM_ACADEMICO
3°  CICLO PROFESIONAL NEGOCIOS INTERNACIONALES     69  0     69
ACTIVIDAD FISICA Y DEPORTE                        162  0    162
ACUICULTURA                                        79  0     79
ADMINISTRACION                                    117  0    117
ADMINISTRACION  FINANCIERA                         74  0     74
...                                               ... ..    ...
TRABAJO SOCIAL                                  12686  0  12686
TRADUCCION INGLES-FRANCES-ESPAÑOL                  68  0     68
TURISMO                                           222  0    222
URBANISMO                                           7  0      7
ZOOTECNIA                                        1669  0   1669

[948 rows x 3 columns]

In [60]:
# Clasificación del Rendimiento global de los estudiantes por programa
# Tabla de distribución de rendimiento por programa académico
tabla_rendimiento = pd.crosstab(
    df['E_PRGM_ACADEMICO'],
    df['RENDIMIENTO_GLOBAL']
)

# Ordenar las columnas
orden = ['bajo', 'medio-bajo', 'medio', 'medio-alto', 'alto']
tabla_rendimiento = tabla_rendimiento.reindex(columns=orden, fill_value=0)

# Agregar columna con el total de estudiantes por programa
tabla_rendimiento['Total'] = tabla_rendimiento.sum(axis=1)

# Ordenar por total (de mayor a menor)
tabla_rendimiento = tabla_rendimiento.sort_values(by='Total', ascending=False)

# Mostrar los primeros 20 programas
print(tabla_rendimiento.head(20))

RENDIMIENTO_GLOBAL                    bajo  medio-bajo  medio  medio-alto  \
E_PRGM_ACADEMICO
DERECHO                              11328       12550      0       13889
ADMINISTRACION DE EMPRESAS           15566       14564      0       12469
CONTADURIA PUBLICA                   12279       12426      0        9950
PSICOLOGIA                            8046        8435      0        7966
INGENIERIA INDUSTRIAL                 4756        6513      0        7742
ADMINISTRACIÓN DE EMPRESAS            9093        8155      0        5453
INGENIERIA CIVIL                      2645        3738      0        5242
MEDICINA                              1368        2412      0        4274
PSICOLOGÍA                            6484        5455      0        3812
INGENIERIA DE SISTEMAS                3805        4340      0        4592
TRABAJO SOCIAL                        5231        3505      0        2540
ENFERMERIA                            3328        3256      0        3125
ARQUITECTURA                          1950        2687      0        3298
ADMINISTRACIÓN EN SALUD OCUPACIONAL   5881        3374      0        1407
CONTADURÍA PÚBLICA                    3791        3731      0        2483
INGENIERIA AMBIENTAL                  1663        2418      0        2961
NEGOCIOS INTERNACIONALES              1214        1823      0        2588
LICENCIATURA EN PEDAGOGIA INFANTIL    4626        2185      0        1116
ECONOMIA                               537         956      0        1690
INGENIERIA MECANICA                    812        1213      0        1743

RENDIMIENTO_GLOBAL                    alto  Total
E_PRGM_ACADEMICO
DERECHO                              15477  53244
ADMINISTRACION DE EMPRESAS            9303  51902
CONTADURIA PUBLICA                    5009  39664
PSICOLOGIA                            7485  31932
INGENIERIA INDUSTRIAL                 9470  28481
ADMINISTRACIÓN DE EMPRESAS            2076  24777
INGENIERIA CIVIL                      7862  19487
MEDICINA                             10045  18099
PSICOLOGÍA                            1626  17377
INGENIERIA DE SISTEMAS                4413  17150
TRABAJO SOCIAL                        1410  12686
ENFERMERIA                            1926  11635
ARQUITECTURA                          3534  11469
ADMINISTRACIÓN EN SALUD OCUPACIONAL    356  11018
CONTADURÍA PÚBLICA                     907  10912
INGENIERIA AMBIENTAL                  2957   9999
NEGOCIOS INTERNACIONALES              3233   8858
LICENCIATURA EN PEDAGOGIA INFANTIL     541   8468
ECONOMIA                              3840   7023
INGENIERIA MECANICA                   3160   6928